### ISSUE TITLE
Sign Up Application Error

### ISSUE THREAD

**Issue by andermarcebr** [vendure-ecommerce/storefront-remix-starter#22]
When I submit form

https://remix-storefront.vendure.io/sign-up

Application Error
Error: Unexpected Server Error
    at dS (worker.mjs:1399:108)
    at async worker.mjs:1531:17
    at async a (worker.mjs:16068:22)
    at async worker.mjs:16072:14
    at async next (worker.mjs:21892:26)

**Comment by andermarcebr** [comment]
Sorry  I reed later about registration
