### ISSUE TITLE
Issue while handling GraphQL errors

### ISSUE THREAD

**Issue by tritao** [vendure-ecommerce/storefront-remix-starter#5]
While trying the storefront and adding Mollie payments, I hit this issue:

```
[1] TypeError: Cannot read properties of undefined (reading 'exception')
[1]     at /home/joao/dev/storefront-remix-starter/app/graphqlWrapper.ts:92:47
[1]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[1]     at action3 (/home/joao/dev/storefront-remix-starter/app/routes/checkout/payment.tsx:48:24)
```

The issue is in this code:

```
            console.log(
                response.errors[0].extensions.exception.stacktrace.join('\n'),
            );
```

There is no extensions field in the error object, so thats why it fails. Where is this supposed to come from?

**Comment by michaelbromley** [comment]
Hi! Thanks for the report. That line of code is making a _lot_ of assumptions about the shape of the error object!

We need to have something a bit more robust here. Would you be interested in making a PR?

**Comment by tritao** [comment]
Hey, sure, I can try sending some improvements once I get back to working on this.
